[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyedautils"
version = "0.0.1"
authors = [
  { name="Reto Marek"},
]
description = "Python Energy Data Analysis Utilities"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/retomarek/pyedautils/"
Issues = "https://github.com/retomarek/pyedautils/issues"