# Jupyter Book configuration
# https://jupyterbook.org/customize/config.html

title: "pyedautils"
author: retomarek
logo: ""
copyright: "2026"

execute:
  execute_notebooks: "auto"
  timeout: 120

repository:
  url: https://github.com/retomarek/pyedautils
  branch: main

launch_buttons:
  thebe: false

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
  config:
    autodoc_member_order: bysource
    napoleon_google_docstring: true
    napoleon_numpy_docstring: false
